
name: GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true 
jobs:
  build:
    name: Build something
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello world!"
